# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApps', '0003_auto_20170409_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='users',
            new_name='user',
        ),
    ]
