# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApps', '0004_auto_20170409_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=20)),
            ],
        ),
    ]
