# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApps', '0005_classes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='classes',
            new_name='course',
        ),
    ]
