# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApps', '0008_loggedinuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
